#!/bin/bash
docker run --rm --name $1 -it -v $(pwd)/envoy_node.yaml:/envoy_node.yaml -v $(pwd)/certs/taskyn-ir.crt:/taskyn-ir.crt -v $(pwd)/certs/taskyn-ir.key:/taskyn-ir.key --network host --memory 128mb --cpuset-cpus 4 envoyproxy/envoy:v1.19.1 -c /envoy_node.yaml

