import { queryGen } from "aba-node";
import { adapterTypes, entityTypes } from "../../types";

export function buildInsertUser(args: adapterTypes.IBuildInsert) {
  const { insert } = args;
  const errorPath = "user service, adapters, insert user";
  const { insertQuery } = queryGen;
  const query = insertQuery({
    table: "users",
    version: "v1",
    values: [
      { column: "id", self: true },
      { column: "username", self: true },
      { column: "phone_number", self: true },
      { column: "first_name", self: true },
      { column: "last_name", self: true },
      { column: "profile_picture_url", self: true },
      { column: "address", self: true },
      { column: "telephone", self: true },
      { column: "problem_description", self: true },
      { column: "gender", self: true },
      { column: "birthday", self: true },
      { column: "marital_status", self: true },
      { column: "marital_state", self: true },
      { column: "education", self: true },
      { column: "academic_field", self: true },
      { column: "religion", self: true },
      { column: "job", self: true },
      { column: "body_diseases", self: true },
      { column: "mind_diseases", self: true },
      { column: "drug_use", self: true },
      { column: "addiction", self: true },
      { column: "is_father_alive", self: true },
      { column: "is_mother_alive", self: true },
      { column: "cousin_marriage", self: true },
      { column: "siblings_position", self: true },
      { column: "siblings", self: true },
      { column: "deactivation_reason", self: true },
      { column: "created_at", self: true },
      { column: "modified_at", self: true },
      { column: "soft_deleted", self: true },
    ],
  });
  return async function insertUser(info: entityTypes.IMadeUserObject) {
    const {
      id,
      username,
      phoneNumber,
      firstName,
      lastName,
      profilePictureUrl,
      address,
      telephone,
      problemDescription,
      gender,
      birthday,
      maritalStatus,
      maritalState,
      education,
      academicField,
      religion,
      job,
      bodyDiseases,
      mindDiseases,
      drugUse,
      addiction,
      isFatherAlive,
      isMotherAlive,
      cousinMarriage,
      siblingsPosition,
      siblings,
      deactivationReason,
      createdAt,
      modifiedAt,
      softDeleted,
    } = info;
    await insert({
      query,
      errorPath,
      params: {
        id,
        username,
        phone_number: phoneNumber,
        first_name: firstName,
        last_name: lastName,
        profile_picture_url: profilePictureUrl,
        address,
        telephone,
        problem_description: problemDescription,
        gender,
        birthday,
        marital_status: maritalStatus,
        marital_state: maritalState,
        education,
        academic_field: academicField,
        religion,
        job,
        body_diseases: bodyDiseases,
        mind_diseases: mindDiseases,
        drug_use: drugUse,
        addiction,
        is_father_alive: isFatherAlive,
        is_mother_alive: isMotherAlive,
        cousin_marriage: cousinMarriage,
        siblings_position: siblingsPosition,
        siblings,
        deactivation_reason: deactivationReason,
        created_at: createdAt,
        modified_at: modifiedAt,
        soft_deleted: softDeleted,
      },
    });
  };
}
